### ISSUE TITLE
Cannot add link to extension after removing it since only urls starting with http are allowed.

### ISSUE THREAD

**Issue by wnrosenberg** [sasikanth513/keyword-redirect#2]
Extension options page starts with "chrome-extension://" so a link to it cannot be created in Keyword Redirect because it doesn't start with "http".

**Comment by sasikanth513** [comment]
Yes.

Chrome method `chrome.tabs.update` only allows few protocols to open in a new tab. "chrome-extension://" is not one of them. I need one too 😞
